### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by reingart** [UniversidadDelEste/recuento_web2py#17]
Crear un controlador especial para inicializar la aplicación:
- titulo y subtitulo (nombre y tipo de elección, fecha, etc.)
- características habilitadas

De ser posible almacenar la configuración en la base de datos (ver app_settings.py)

**Comment by marian-vignau** [comment]
Al importar el controlador default.py, revisa si está configurada la aplicacion (tiene titulo y subtitulo) en un archivo titulos.json, si no existe el archivo abrir un form en el index.html que requiere la informacion necesaria.

Falta:
¿Qué significa características habilitadas? ¿Qué clase de características?
Que los datos están almacenados en la base de datos.

**Comment by marian-vignau** [comment]
""Puede ser en un archivo ini, json, o .py
Yo recomendaría ir por el lado de models/app_settings.py (que lea un archivo ini/json), aunque también puedes ver el paquete contribuido appconfig.py que ya procesa private/appconfig.ini
Podrías hacer un controlador setup.py que modifique el archivo ini/json con un formulario simple.
De hecho, un método write_config para la clase AppConfig posiblemente sería un buen aporte al proyecto web2py ... 
Respecto las características, sería que controlador/función está habilitada (más allá de los permisos generales).
Por ej, no tiene sentido mostrar la parte de telegramas si no se van a utilizar. En ese caso, habría que habilitar solo reportes y en todo caso la pantalla de planillas en modo solo lectura (sin casilleros para carga de datos)."" M.Reingart

Se agrega en el menu Admin un controlador setup.py, que tiene una función index y su correspondiente vista setup/index.html. Se expone titulo, subtitulo, fecha y lugar de la elección, y más abajo aparece el arbol de menues, para permitir habilitar cada una de las funciones disponibles.
Una vez que el usuario modifica todo lo que desea, se graba en el modelo app_settings.py, y se actualiza automáticamente la aplicación al releer la homepage .

En el modelo de menues, se filtran los menues inhabilitados para evitar que las caracteristicas asociadas a ellos queden visibles.

La lectura, grabacion de seteos y el filtrado de menues se realizan en un modulo denominado manage_settings.py, donde se aisla todo el procesamiento para evitar complicar la vista o el controlador.

**Comment by reingart** [comment]
El enfoque para grabar los settings es interesante c8d3d5d, pero creo que no tendría que modificar el código. En vez de modificar app_settings.py y hacer un execfile, podrías guardarlo en un json o ini
