### ISSUE TITLE
Ayuda en linea

### ISSUE THREAD

**Issue by reingart** [UniversidadDelEste/recuento_web2py#21]
Incorporar algún mecanismo de ayuda en linea (ya sea con indicaciones visuales paso a paso, ventanas emergentes, vídeos demostrativos, etc.)

**Comment by csisek** [comment]
Se consignará un mensaje de ayuda para conocer los requierimientos de cada ítem del menú

**Comment by csisek** [comment]
Se cargaron mensajes de ayuda
